services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
